(function(){
    Component.call(this,[
        this.turret=new Drawable({
            src:"assets/ground-cannon.json",
            frame:"turret",
            transform:{pivot:{
                x:77,
                y:252-173
            }},
            pos:{x:117}
        }),
        this.body=new Drawable({
            src:"assets/ground-cannon.json",
            frame:"body",
            transform:{pivot:{
                x:117,
                y:0
            }}
        })
    ],{
        transform:{pivot:{y:160},scale:{x:0.5,y:0.5}}
    })
    this.start=function(){
        this.body.addChild(this.turret);
        this.addChild(this.body);
        this.pos.x=window.innerWidth/2;
        this.pos.y=window.innerHeight;
    }
})